env:
  global:
    - CC_TEST_REPORTER_ID=9780d4f67eb3f89b628ca4816a8d4f36a2d08cdcbd436586dc0695afb54fd523
language: node_js
node_js:
- '10'

dist: trusty

cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database quickcredit_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - "npm run nyc"

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  email: false
