const users = [
  {
    id: 1,
    email: 'fnduamaka@gmail.com',
    firstName: 'Francis',
    lastName: 'Nduamaka',
    password: '$2b$10$fLRpj4WVXjosvWRB7ME6OeRrZpjT1uADaP9cOZUnX6m1Deb3HjAXa',
    address: 'Km 10 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 2,
    email: 'baz@gmail.com',
    firstName: 'Bastieno',
    lastName: 'Nduamaka',
    password: '$2b$10$Sx/vGH1vPjVCzH6pqybpW.QTFuNTfzhSYU3wkLUZ3joKOnq6.XLp2',
    address: 'Km 11 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    email: 'kimble@gmail.com',
    firstName: 'Kimble',
    lastName: 'Okoye',
    password: '$2b$10$FFf3q2n9IXSaKjR4pT.AZevg9BohZx1qPTgTeEdw1JP0uDzbFKqly',
    address: 'Km 12 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 4,
    email: 'gwinters@gmail.com',
    firstName: 'Garrett',
    lastName: 'Winters',
    password: '$2b$10$Lq0I0FssszcqmqA03tN5w.92vPTwMTk3AHRXehwD6JxX.vgW9QxCu',
    address: 'Km 13 Airport Road, Galadimawa, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 5,
    email: 'amara@gmail.com',
    firstName: 'Amara',
    lastName: 'Uba',
    password: '$2b$10$Lq0I0FssszcqmqA03tN5w.92vPTwMTk3AHRXehwD6JxX.vgW9QxCu',
    address: 'Km 14 Airport Road, Galadimawa, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 6,
    email: 'chisom@gmail.com',
    firstName: 'Chisom',
    lastName: 'Anih',
    password: '$2b$10$Lq0I0FssszcqmqA03tN5w.92vPTwMTk3AHRXehwD6JxX.vgW9QxCu',
    address: 'Km 15 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 7,
    email: 'uche@gmail.com',
    firstName: 'Uche',
    lastName: 'Njoku',
    password: '$2b$10$Lq0I0FssszcqmqA03tN5w.92vPTwMTk3AHRXehwD6JxX.vgW9QxCu',
    address: 'Km 15 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 8,
    email: 'joe@gmail.com',
    firstName: 'Joseph',
    lastName: 'Stones',
    password: '$2b$10$Lq0I0FssszcqmqA03tN5w.92vPTwMTk3AHRXehwD6JxX.vgW9QxCu',
    address: 'Km 15 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
];

export default users;
