const users = [
  {
    email: 'admin@quickcredit.com',
    firstName: 'Admin',
    lastName: 'Super',
    password: '$2b$10$ZVg6ysb/fir1haOEU0v7G.KwmV0eyFE0eQAotuQRjRZ7ny8DVq0/y',
    address: 'Km 9 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: true,
  },
  {
    email: 'fnduamaka@gmail.com',
    firstName: 'Francis',
    lastName: 'Nduamaka',
    password: '$2b$10$C86TKxejWYKfKllCTFnIaOW0Av0WIJT0S8lWptX8ZSAAVxcCMO6Ti',
    address: 'Km 10 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: true,
  },
  {
    email: 'baz@gmail.com',
    firstName: 'Bastieno',
    lastName: 'Nduamaka',
    password: '$2b$10$JDmLCmDeSuJUbnqRB4x6vu7Mqe9U5ZkBYLTa.DQdT6j.Jo6PYafRK',
    address: 'Km 11 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    email: 'kimble@gmail.com',
    firstName: 'Kimble',
    lastName: 'Okoye',
    password: '$2b$10$aa9rmKB9QAmqGL3i4ojohu8ByDPTs9E2pxjBENailjBlMsz0SJkrG',
    address: 'Km 12 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    email: 'gwinters@gmail.com',
    firstName: 'Garrett',
    lastName: 'Winters',
    password: '$2b$10$U9Fk0ftarzkTl/90cZyaCuNEsxAoWhpTQkA0tqWTMYVWMTdG4oBaC',
    address: 'Km 13 Airport Road, Galadimawa, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    email: 'amara@gmail.com',
    firstName: 'Amara',
    lastName: 'Uba',
    password: '$2b$10$U9Fk0ftarzkTl/90cZyaCuNEsxAoWhpTQkA0tqWTMYVWMTdG4oBaC',
    address: 'Km 14 Airport Road, Galadimawa, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    email: 'chisom@gmail.com',
    firstName: 'Chisom',
    lastName: 'Anih',
    password: '$2b$10$U9Fk0ftarzkTl/90cZyaCuNEsxAoWhpTQkA0tqWTMYVWMTdG4oBaC',
    address: 'Km 15 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    email: 'uche@gmail.com',
    firstName: 'Uche',
    lastName: 'Njoku',
    password: '$2b$10$U9Fk0ftarzkTl/90cZyaCuNEsxAoWhpTQkA0tqWTMYVWMTdG4oBaC',
    address: 'Km 16 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    email: 'joe@gmail.com',
    firstName: 'Joseph',
    lastName: 'Stones',
    password: '$2b$10$U9Fk0ftarzkTl/90cZyaCuNEsxAoWhpTQkA0tqWTMYVWMTdG4oBaC',
    address: 'Km 17 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
  {
    email: 'ola@gmail.com',
    firstName: 'Olajide',
    lastName: 'Adeyemi',
    password: '$2b$10$U9Fk0ftarzkTl/90cZyaCuNEsxAoWhpTQkA0tqWTMYVWMTdG4oBaC',
    address: 'Km 18 Airport Road, Galadimawa, Abuja',
    status: 'unverified',
    isAdmin: false,
  },
  {
    email: 'cynthia@gmail.com',
    firstName: 'Cynthia',
    lastName: 'Osuala',
    password: '$2b$10$JDmLCmDeSuJUbnqRB4x6vu7Mqe9U5ZkBYLTa.DQdT6j.Jo6PYafRK',
    address: 'Km 11 Airport Road, Galadimawa, Abuja',
    status: 'verified',
    isAdmin: false,
  },
];

export default users;
